[apt]
general = [
  "autoconf",
  "automake",
  "build-essential",
  "cmake",
  "curl",
  "docker",
  "docker-compose",
  "git",
  "gnupg2",
  "htop",
  "iputils-ping",
  "jq",
  "libevent-dev",
  "libncurses5-dev",
  "man",
  "net-tools",
  "netcat-openbsd",
  "p7zip-full",
  "tzdata",
  "unar",
  "unzip",
  "vim",
  "wget",
  "zsh",
 ]
asdf = [
  "libreadline-dev",
  "libssl-dev",
  "zlib1g-dev",
]
tmux = [
  "byacc",
  "pkg-config",
]
pynvim = [
  "libffi-dev",
]

# asdf
[tool_versions]
tmux = ["3.1a"]
ruby = ["2.7.1"]
python = ["3.8.2", "2.7.16"]
rust = ["1.43.0"]
java = ["adopt-openjdk-13.0.2+8"]
nodejs = ["14.1.0"] # needed for vim-coc
yarn = ["1.22.4"] # needed for vim-coc

[ruby]
gems = [
  "bundler",
  "rake",
  "pry",
  "pry-byebug",
  "pry-rescue",
  "neovim",
]

[python]
packages = [
  "pynvim",
]
