# vi: ft=Dockerfile

FROM debian:buster

# Locales
ENV LANG=en_US.UTF-8

RUN apt-get update && apt-get install -y locales
RUN sed -i -e 's/# en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/' /etc/locale.gen
RUN locale-gen en_US.UTF-8

# Colors and italics for tmux
COPY xterm-256color-italic.terminfo /root
RUN tic /root/xterm-256color-italic.terminfo
ENV TERM=xterm-256color-italic

# Common packages
RUN apt-get update
<% tools_for_source("apt").keys.each do |package| %>
RUN apt-get install -y <%= package -%>
<% end -%>

SHELL ["/bin/bash", "-c"]

WORKDIR /root

# install neovim
WORKDIR /root/.local/bin/nvim
RUN curl -LO https://github.com/neovim/neovim/releases/download/stable/nvim.appimage
RUN chmod u+x nvim.appimage
RUN ./nvim.appimage --appimage-extract

# asdf
WORKDIR /root
COPY tool-versions /root/.tool-versions

RUN git clone https://github.com/asdf-vm/asdf.git ~/.asdf --branch v0.7.8
RUN echo -e '\n. $HOME/.asdf/asdf.sh' >> ~/.bashrc
RUN echo -e '\n. $HOME/.asdf/completions/asdf.bash' >> ~/.bashrc
RUN echo -e '\n. $HOME/.asdf/asdf.sh' >> ~/.zshrc
RUN echo -e '\n. $HOME/.asdf/completions/asdf.bash' >> ~/.zshrc

<% tools_for_source("asdf").each do |tool, config| %>
<% if config["apt_dependencies"] %>
<% config["apt_dependencies"].each do |package| %>
RUN apt-get install -y <%= package -%>
<% end -%>
<% end -%>

RUN /root/.asdf/bin/asdf plugin-add <%= tool -%>
<% if config["pre_install_commands"] -%>
<% config["pre_install_commands"].each do |cmd| %>
RUN /bin/bash <%= cmd -%>
<% end -%>
<% end -%>

<% config["asdf"]["versions"].each do |version| %>
RUN PATH=/root/.asdf/bin:$PATH asdf install <%= tool -%> <%= version -%>
<% end -%>
<% end -%>

<% package_configs.each do |pc| %>
<% pc["install_list"].each do |package| %>
RUN PATH=/root/.asdf/shims:/root/.asdf/bin:$PATH <%= pc["install_command"] -%> <%= package -%>
<% end -%>
<% end -%>


RUN PATH=/root/.asdf/shims:/root/.asdf/bin:$PATH asdf reshim

# Dotfiles 😎
WORKDIR /root/dotfiles
COPY dotfiles /root/dotfiles
# don't install nvim plugins yet; the rake task shells out, and we need to
# define a "nvim" function to run the AppImage.
RUN PATH=/root/.asdf/shims:/root/.asdf/bin:$PATH rake scripts:install configs:install docker_env:install
RUN printf "nvim() {\n  /root/.local/bin/nvim/squashfs-root/AppRun \"\$@\"\n}\n" >> ~/.aliases_shared
# source the function we just defined
RUN sed -i 's/bash -c/BASH_ENV=~\/.aliases_shared bash -c/g' /root/dotfiles/Rakefile
RUN PATH=/root/.asdf/shims:/root/.asdf/bin:$PATH rake plugins:install

RUN echo . $HOME/.asdf/asdf.sh >> ~/.aliases_shared
RUN /bin/zsh -c 'printf "fpath=(${HOME}/.asdf/completions ${fpath})\nautoload -Uz compinit\ncompinit" >> ~/.zshrc'

WORKDIR /root
CMD /bin/bash -i -c "tmux-start dev"
