#!/usr/bin/env ruby
# vi: ft=ruby

require "erb"
require "toml-rb"
require "pry-byebug"

TOOLS_FILE = File.join(__dir__, "Tools.toml")
DOCKERFILE_TEMPLATE_FILE = File.join(__dir__, "Dockerfile.erb")
ARTIFACTS_DIR = File.join(__dir__, "artifacts")

class Generator
  attr_accessor :tools, :dockerfile_template
  def initialize
    @tools = TomlRB.load_file(TOOLS_FILE)
    @dockerfile_template = ERB.new(File.read(DOCKERFILE_TEMPLATE_FILE), trim_mode: "-")
  end

  def run
    File.write(
      File.join(ARTIFACTS_DIR, "Dockerfile"),
      dockerfile_template.result(binding),
    )

    File.write(
      File.join(ARTIFACTS_DIR, "tool-versions"),
      asdf_tool_versions,
    )
  end

  def asdf_tool_versions
    tools_for_source("asdf").map do |tool, config|
      (Array(tool) + config["asdf"]["versions"]).join(" ")
    end.join("\n")
  end

  def tools_for_source(source)
    tools.filter { |_, config| config["source"] == source }
  end

  def package_configs
    tools
      .values
      .filter_map { |config| config["packages"] }
  end
end

Generator.new.run
