[apt]
source = false

  [apt.as_source]
  pre_usage_commands = [
    "apt-get update",
  ]
  usage_command = "apt-get install -y"

[asdf]
source = "git"
git.repo = "https://github.com/asdf-vm/asdf.git"
git.release = "0.7.8"
dependencies = [
  "libreadline-dev",
  "libssl-dev",
  "zlib1g-dev",
]

  [asdf.as_source]
  pre_usage_commands = [
    "echo -e '\n. $HOME/.asdf/asdf.sh' >> ~/.bashrc",
    "echo -e '\n. $HOME/.asdf/completions/asdf.bash' >> ~/.bashrc"
  ]
  usage_command = "asdf install"

[appimage]
source = "curl"

  [appimage.as_source]
  usage_command = "curl -LO"

[autoconf]
source = "apt"

[automake]
source = "apt"

[build-essential]
source = "apt"

[cmake]
source = "apt"

[curl]
source = "apt"

[docker]
source = "apt"

[docker-compose]
source = "apt"

[git]
source = "apt"

  [git.as_source]
  usage_command = "git clone"

[gnupg2]
source = "apt"

[htop]
source = "apt"

[iputils-ping]
source = "apt"

[jq]
source = "apt"

[libevent-dev]
source = "apt"

[libncurses5-dev]
source = "apt"

[man]
source = "apt"

[net-tools]
source = "apt"

[netcat-openbsd]
source = "apt"

[p7zip-full]
source = "apt"

[tzdata]
source = "apt"

[unar]
source = "apt"

[unzip]
source = "apt"

[vim]
source = "apt"

[wget]
source = "apt"

[zsh]
source = "apt"

[tmux]
source = "asdf"
asdf.versions = ["3.1a"]
apt_dependencies = [
  "byacc",
  "pkg-config",
]

[python]
source = "asdf"
asdf.versions = ["3.8.2", "2.7.16"]
apt_dependencies = [
  "libffi-dev",
  "liblzma-dev",
  "libncurses5-dev",
  "libncursesw5-dev",
  "libreadline-dev",
  "libsqlite3-dev",
  "libssl-dev",
  "llvm",
  "python-openssl",
  "tk-dev",
  "xz-utils",
  "zlib1g-dev",
]
packages.install_command = "pip3 install"
packages.install_list = [
  "pynvim",
]

[ruby]
source = "asdf"
asdf.versions = ["2.7.1"]
packages.install_command = "gem install"
packages.install_list = [
  "bundler",
  "rake",
  "pry",
  "pry-byebug",
  "pry-rescue",
  "neovim",
]

[rust]
source = "asdf"
asdf.versions = ["1.43.0"]

[java]
source = "asdf"
asdf.versions = ["adopt-openjdk-13.0.2+8"]

[nodejs]
source = "asdf"
asdf.versions = ["14.1.0"] # needed for vim-coc
pre_install_commands = [
  "~/.asdf/plugins/nodejs/bin/import-release-team-keyring",
]

[yarn]
source = "asdf"
asdf.versions = ["1.22.4"] # needed for vim-coc
